# Generated by Django 3.0.4 on 2020-03-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='intnotation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subnet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sj.Subnet'),
        ),
    ]
