# Generated by Django 3.0.4 on 2020-03-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sj', '0002_auto_20200313_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='intnotation',
            field=models.IntegerField(default=0),
        ),
    ]
